# Generated by Django 3.1.2 on 2020-11-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_from',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='user_to',
            new_name='following',
        ),
    ]
