# Generated by Django 3.1.2 on 2020-12-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201128_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='no_image.png', upload_to='users/%Y/%m/%d'),
        ),
    ]
