# Generated by Django 3.1.2 on 2020-12-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201203_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='work as',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
