# Generated by Django 3.1.2 on 2020-12-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20201203_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditAccount',
        ),
    ]
