# Generated by Django 3.1.2 on 2020-12-03 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20201203_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_of_birth',
            new_name='Born',
        ),
    ]
