# Generated by Django 3.1.2 on 2020-12-20 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20201220_1705'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
