# Generated by Django 3.1.2 on 2020-12-22 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0008_auto_20201222_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='like_count',
        ),
        migrations.AlterField(
            model_name='upload',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
